### ISSUE TITLE
Main fab icon color

### ISSUE THREAD

**Issue by swapnil-gawali** [leinardi/FloatingActionButtonSpeedDial#111]
How to change main fab icon color, i have added white icon but still its showing black, app:tint, android:tint also not working.

**Comment by leinardi** [comment]
Currently the main fab tinting is not supported.

**Comment by RingoMckraken** [comment]
I'm having the same issue, imported a vector asset that is white but still showing black. Is this on the road map to be supported?

**Comment by untungs** [comment]
I was able to change the icon tint programmatically (Kotlin).

`speedDial.mainFab.imageTintList = ColorStateList.valueOf(Color.WHITE)`

Note that the getMainFab() method returns `com.google.android.material.floatingactionbutton.FloatingActionButton` instead of `android.support.design.widget.FloatingActionButton`, probably due to this setting in gradle.properties.

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by TBoehm** [comment]
@untungs have you found a solution to tint the action items too? Or is the only solution to add/tint them programatically?

**Comment by cylonu87** [comment]
I was able to tint it with a style, AppTheme is the theme of the activity:

```
<style name="AppTheme" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
   ...
    <item name="colorOnSecondary">@color/white</item>
</style>
```

**Comment by swapnil-gawali** [comment]
As mentioned by @untungs , this worked for me (JAVA)

`speedDial.getMainFab().setSupportImageTintList(ColorStateList.valueOf(getResources().getColor(R.color.colorPrimaryDark)));`

**Comment by TBoehm** [comment]
thx @cylonu87 that worked :)
