### ISSUE TITLE
Reduce min api to 14

### ISSUE THREAD

**Issue by jahirfiquitiva** [leinardi/FloatingActionButtonSpeedDial#31]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

I don't think the project would suffer much from setting a lower min api level, plus it could be used by more projects :smiley: 

Thanks

**Comment by leinardi** [comment]
Fair enough. I skipped API 14 because I cannot test on it (I tried to use the AVD but they don't even boot on API 14 with the latest Emulator) and since this API level isn't even mentioned in the [Dashboard](https://developer.android.com/about/dashboards/index.html) I thought it wasn't a problem to just drop it.

But if you think it will be better to have it, I will add it on the next alpha04 :+1: .

**Comment by jahirfiquitiva** [comment]
Great! Thank you :smile:
