### ISSUE TITLE
Close animation duration is too short

### ISSUE THREAD

**Issue by jahirfiquitiva** [leinardi/FloatingActionButtonSpeedDial#45]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe the problem:

Hello
I think the close animation duration is too short that said animation is basically inexistent. I'm not sure if it's the duration or actually lack of animation.

I think when closing the SpeedDialView, the animation should be the same as when opening, just in reverse order.

Maybe an option to enable/disable it could suffice, but I think having both could look better.

#### Steps to reproduce:

  1. Open sample app
  2. Press main FAB button to open the SpeedDialView
  3. Press main FAB button to close the SpeedDialView

**Comment by leinardi** [comment]
Hey, actually there is a closing animation and is the same that you can see in the [Material Design](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions) guidelines and in Inbox by Gmail. The animation is a fade and the length is the one of a short animation: https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/31ea2622ac99b79a456dd5acb3dae69613956500/library/src/main/java/com/leinardi/android/speeddial/UiUtils.java#L125
I agree with the guideline and I don't think should be longer bu I will try to make the length customizable so that can be changed overriding a resource. Can this work for you?

**Comment by jahirfiquitiva** [comment]
@leinardi 
I knew you were going to say that it was made that way because of that, but I still think the same animation but reversed would look better.
And as I mentioned in the first comment, an option to enable/disable it would be perfect for those who might not like it.

**Comment by leinardi** [comment]
Hi @jahirfiquitiva, you can set a custom value for the duration overriding this values:

```
<resources>
    <integer name="sd_close_animation_duration">200</integer>
    <integer name="sd_open_animation_duration">200</integer>
    <integer name="sd_rotate_animation_duration">200</integer>
</resources>
```

**Comment by jahirfiquitiva** [comment]
@leinardi 
I don't think that could suffice if the animation is a simple fade. 😕

Is it possible that you can make an option to use the same animation as opening, but in reverse order? 🤔🙏🏻

**Comment by leinardi** [comment]
I will keep it in mind but currently is not something that I can work on any time soon. But feel free to make a PR for this feature (just be sure to allow the user to set this from both XML and programmatically and, by default, should be the current animation).
