### ISSUE TITLE
make addActionItem() return instance of menu item

### ISSUE THREAD

**Issue by ashif-ismail** [leinardi/FloatingActionButtonSpeedDial#69]
Please modify the addActionItem() method to return the instance of the menu button,so that we can manipulate this item else where.

example : 
`ActionItem item = mSpeedDialView.addActionItem(new SpeedDialActionItem.Builder(R.id.menuHafilatMachines,R.drawable.pay_mawaqif)
                .setFabBackgroundColor(getColor(R.color.colorPrimary))
                .setLabel(getString(R.string.hafilat_ticket_machine))
                .setLabelColor(getResources().getColor(R.color.colorText))
                .setLabelClickable(false)
                .create());`

so,somewhere else we could do like this 
`item.doSomething()`

PLEASE,TAKE THIS ON PRIORITY

**Comment by leinardi** [comment]
Hi @SheikhZayed, the `SpeedDialActionItem` are immutable so you can only get the properties you set with the builder. I just want to clarify that, even if you have the instance of the item somewhere else, it will not be possible to change that item but just to read the properties.

**Comment by ashif-ismail** [comment]
ok,it would better if SpeedDialActionItem subclass Android Button..just a suggestion

will be helpfull with the out of the box button properties

rather than making it a parcelable class

**Comment by leinardi** [comment]
Now that I read your issue better, I am afraid I cannot accept it because internally the library is not using the `MenuItem` objects, so there is no way that I can return any useful instance of it.
When I first read it I thought you wanted to have back an instance of `SpeedDialActionItem`, which doesn't make much sense since is a mandatory parameter of the method.
