### ISSUE TITLE
Doesn't change label text language when app language is changed dynamically

### ISSUE THREAD

**Issue by ashif-ismail** [leinardi/FloatingActionButtonSpeedDial#79]
I have noticed a bug in this library which makes the label text doesn't change the label text to the current locale if the app language is changed dynamically.(even if referenced from strings.xml)

however,the floating menus correctly change the test label after the next restart of the app.

please fix this

**Comment by leinardi** [comment]
Hi @SheikhZayed, what do you mean by "even if referenced from strings.xml"? 

The SpeedDialActionItem builder only provides a String setter for the label:
https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/master/library/src/main/java/com/leinardi/android/speeddial/SpeedDialActionItem.java#L183

I have no way to know from which string resource that String comes from or even if it was from a string resource or not.

Unfortunately you have to handle the language change yourself, listening for it and updating all strings if that happens.

I will keep this as a feature request but I am not sure if and when will be implemented.

**Comment by ashif-ismail** [comment]
what do you mean by "even if referenced from strings.xml"?

> speedDialInstance.setLabel(getString(R.string.something));

I handle the dynamic language change and respectively update all the strings in the app,but the labels for the fab doesn't get changed(all others does) even though the main fab changes the position (from LTR to RTL)

the labels in the fab only changes the text to the respective updated language once i restart the app 

what could be the issue?
Any hackfix,please (nearing the release.. :( )

**Comment by leinardi** [comment]
As I said, you need to handle manually the labels, this means setting all of them again when there is a language change.

You could, for example, add to your Manifest the attribute `android:configChanges="layoutDirection|locale"` to the Activity that has the Speed Dial and than override the `onConfigurationChanged()` method and there refresh the strings.
By refreshing the strings I mean you have to replace all the items you already have with new items having the updated strings.

I know this is not the best solution but is the only workaround I can think until this is properly handled from the library.

**Comment by ashif-ismail** [comment]
when i update the language, i call recreate() to restart the root activity which pass through the oncreate() which has a method in which i add items to FAB.

is this not enough ? do i manually override onConfigurationChanged() ?

**Comment by leinardi** [comment]
Ok, I think I fix the issue but it requires a [change in the API](https://github.com/leinardi/FloatingActionButtonSpeedDial/commit/e5366623b722cd04d6c8ecd3040385b9af18ac71#diff-4f26bd84507a873ea0ac8366d22db54aR81) of the lib, that implies going from version 1.x to version 2.x. So I will wait before merging and releasing this fix until I have more API breaking changes.

Meanwhile you can try it using jitpack: https://jitpack.io/#leinardi/FloatingActionButtonSpeedDial/feature~#79-dynamic-language-switch-SNAPSHOT

If there are issues with the branch name due to the special chars, try using the commit hash:
`implementation 'com.github.leinardi:FloatingActionButtonSpeedDial:e5366623b7'`

Please let me know if this fixes the issue for you.

**EDIT**
In case is not clear, now you can set directly the String Res integer as label.

Old way:
`speedDialInstance.setLabel(getString(R.string.something));`
New way:
`speedDialInstance.setLabel(R.string.something);`

**Comment by ashif-ismail** [comment]
sure,thanks for the quick response...i'll get back to you soon

**Comment by ashif-ismail** [comment]
great ! it really works .. thank you very much .. 💯 
can i use this 

> implementation 'com.github.leinardi:FloatingActionButtonSpeedDial:e5366623b7'

in my app gradle and release the app to production ? will it break anytime ?

**Comment by leinardi** [comment]
That should be relatively safe (of course if the jitpack service goes down it will break new builds, but the same applies to the official jcenter server).

Just keep in mind to manually check for new versions of the lib every now and than because, if you use jitpack, you will not get any notifications for new releases.

PS
When your app goes live could you please give me a like where I can see it? I am just curious to see how it looks :)

**Comment by ashif-ismail** [comment]
sure,i'll update the store link here itself,

do you have any roadmap / expected date on which you can merge this change to stable version of library ?

**Comment by leinardi** [comment]
> do you have any roadmap / expected date

Unfortunately not, as I said I would like to collect more API breaking changes before merging this and, so far, this is the only one.

**Comment by ashif-ismail** [comment]
ok,i will watch this repo until last week of my app release,if you dont release the stable version,i will use this library locally as a module and build :(

i cant take a chance to break at anytime..

thanks for your great help and awesome work 👍

**Comment by ashif-ismail** [comment]
as requested,here's the link to our app : [https://play.google.com/store/apps/details?id=com.dot.darbmobile](url)

map might not work,as it is only configured to work in UAE,but you can check the behaviour of your library

**Comment by leinardi** [comment]
Thanks for the link :+1:

**Comment by leinardi** [comment]
Just FYI, I published version 2.0.0 that includes the fix for this issue: https://github.com/leinardi/FloatingActionButtonSpeedDial/releases/tag/2.0.0

**Comment by ashif-ismail** [comment]
Great👏

**Comment by BrightVan** [comment]
i think you should edit the README.md，give a tip about this. And add @Deprecated on method setLabel(@Nullable String label).
otherwise, somebody will get this problem in someday.
